name: Deploy to shinyapps.io
on:
  # run on any push 
  push:
  # run on request (via button in actions menu)
  workflow_dispatch:
      
jobs:
  deploy:
    name: Deploy to shinyapps

    # allow skipping deployment for commits containing '[WIP]' or '[no-deploy]' in the commit message
    if: "!contains(github.event.head_commit.message, '[WIP]') && !contains(github.event.head_commit.message, '[no-deploy]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up R2u (faster dependency installation)
        uses: eddelbuettel/github-actions/r2u-setup@master

      - name: Deploy App
        run: |
          install.packages(c('shiny', 'rsconnect'))
          warning("Dep identified: ", renv::dependencies()$Package)
          install.packages(renv::dependencies()$Package)
          rsconnect::setAccountInfo(name='lukaswallrich', token='${{secrets.SHINYAPPS_TOKEN}}', secret='${{secrets.SHINYAPPS_SECRET}}')
          rsconnect::deployApp(appName = 'fred_explorer', appDir = '.', forceUpdate = TRUE, envManagementR = TRUE)
        shell: Rscript {0}



