name: Deploy to shinyapps.io
on:

  # run on any push 
  push:

  # run on request (via button in actions menu)
  workflow_dispatch:
      
jobs:
  deploy:
    name: Deploy to shinyapps

    # allow skipping deployment for commits containing '[WIP]' or '[no-deploy]' in the commit message
    if: "!contains(github.event.head_commit.message, '[WIP]') && !contains(github.event.head_commit.message, '[no-deploy]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        uses: qwert666/shinyapps-actions@main
        env:
            SHINY_USERNAME: 'lukaswallrich'
            SHINY_TOKEN: ${{ secrets.SHINYAPP_TOKEN }}
            SHINY_SECRET: ${{ secrets.SHINYAPP_SECRET }}
            APP_NAME: 'fred_explorer'
            APP_DIR: ''